import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Login } from '../components'
import { useContext, useEffect } from 'react'
import { UserContext } from '../shared/contexts/UserContext'
import { auth } from '../lib/firebase'

const StartPage: NextPage = () => {
    
    const { setUserLog, USER_INITIAL } = useContext(UserContext);

    useEffect(() => {
      const unsubscribeAuth = auth.onAuthStateChanged((user) => {
       setUserLog(user|| USER_INITIAL);
      });
      return () => {
        unsubscribeAuth();
      };
    }, [setUserLog, USER_INITIAL]);
  return (
    <div className={styles.container}>
      <Head>
        <title>App Play Green</title>
        {/* <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />   */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Login/>
      </main>


    </div>
  )
}

export default StartPage
